### ISSUE TITLE
Question about trailing modifiers format

### ISSUE THREAD

**Issue by fanavarro** [owlcollab/oboformat#114]
Hi all. I would like to ask you a question about trailing modifiers in OBO ontologies.

The OBO parser in OWLAPI is showing warning messages indicating that qualifier values should be enclosed by quotes. I have searched information on this and what I have found is the following example from [OBO 1.2 specification](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html#S.2.2.3):

`[GO:ma, GO:midori "Midori was drinking and came up with this", GO:john {namespace=johnsirrelevantdbxrefs}]`

They are setting an unquoted text for a trailing modifier value. For its part, I have not found an example for OBO 1.4.

My question is what is the correct format for trailing modifiers?

Regards and thanks so much for your time,
Fran.

**Comment by althonos** [comment]
Hi @fanavarro,

The correct format for trailing qualifiers is indeed that values are quote-enclosed: if you look at the [Syntax and Semantics Draft](http://owlcollab.github.io/oboformat/doc/obo-syntax.html) you'll see the following definition for the `Qualifier` production rule:
```
Qualifier ::= Rel-ID '=' QuotedString
```

**Comment by fanavarro** [comment]
Hi @althonos and thanks for your quick answer, it has solved my doubt.

Greetings and thanks again for your time.
