### ISSUE TITLE
unable to convert owl format to obo

### ISSUE THREAD

**Issue by lmanchon** [owlcollab/oboformat#121]
-Hi,

last version of robot failed to convert this owl file:
https://raw.githubusercontent.com/stemcellontologyresource/OSCI/master/src/ontology/osci.owl

is there a specific parameter i need to add ? Thank you.

java -jar ./robot.jar convert --input osci.owl --format obo --output osci.obo

ERROR Input ontology contains 3 triple(s) that could not be parsed:

    http://purl.obolibrary.org/obo/OBI_0000958 http://www.w3.org/1999/02/22-rdf-syntax-ns#type _:genid2147487981.
    http://purl.obolibrary.org/obo/OBI_0000998 http://www.w3.org/1999/02/22-rdf-syntax-ns#type _:genid2147487983.
    http://purl.obolibrary.org/obo/OBI_0000979 http://www.w3.org/1999/02/22-rdf-syntax-ns#type _:genid2147487982.

OBO STRUCTURE ERROR Ontology does not conform to OBO structure rules:
multiple def tags not allowed. in frame:Frame(CLO:0000001 id( CLO:0000001)comment( A 'cell line cell' is a part of a cell line established through the passaging/selection of a primary cultured cells or the experimental modification of an existing cell line. New types of cell line cells are established after sufficient passaging of a primary culture to establish a stable and homogenous population that qualifies as a line (typically 1-20 passages), or following some spontaneous or experimental modification that confers novel characteristics to an existing line. A cell line cell typically has mutations of five or more genes compared to the original cell that derives the cell line cell. Some gene mutations may turn on some oncogenes. Cell line cells can be in active culture, stored in a quiescent state for future use (e.g. frozen in liquid nitrogen), or applied in experimental procedures. )name( cell line cell)property_value( IAO:0000111 cell line cell xsd:string)def( A cultured cell that is part of a cell line - a stable and homogeneous population of cells with a common biological origin and propagation history in culture)def( A cultured cell that is part of a cell line - a stable and homogeneous population of cells with a common biological origin and propagation history in culture
)property_value( IAO:0000412 http://purl.obolibrary.org/obo/clo.owl)property_value( IAO:0000117 Yongqun He, Matthew Brush, Sirarat Sarntivijai, Alexander Diehl, Jie Zheng, Yu Lin, Bjoern Peters xsd:string)property_value( IAO:0000412 http://purl.obolibrary.org/obo/obi.owl)relationship( RO:0001000 CL:0000001)is_a( OBI:0001866{{is_inferred=true} }))
For details see: http://robot.obolibrary.org/errors#obo-structure-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.

**Comment by matentzn** [comment]
I answered this here, much the same people listen here and there: https://github.com/ontodev/robot/issues/1001
