### ISSUE TITLE
Properties in axiom annotations always get wrong IRI

### ISSUE THREAD

**Issue by cmungall** [owlcollab/oboformat#125]
Properties in axiom annotations always get wrong IRI (e.g. seeAlso)
It is currently impossible to uses a specific external IRI (e.g. skos:exactMatch) for the property of an axiom annotation)

from @balhoff 

See also:

- #132

**Comment by balhoff** [comment]
This should now work due to https://github.com/owlcs/owlapi/pull/1099.
